@extends('layouts.app')
@section('title',$country->name)
@section('heading','Detail Negara')
@section('content')
<div class="d-flex flex-wrap align-items-center gap-3 mb-4"><img src="{{ $country->flag_url }}" style="width:80px;height:52px;object-fit:cover;border-radius:8px" alt=""><div><h2 class="page-title">{{ $country->name }}</h2><p class="text-muted mb-0">{{ $country->official_name }}</p></div><div class="ms-auto d-flex gap-2"><button id="watchCountry" class="btn btn-outline-warning"><i class="bi bi-star"></i> Pantau AJAX</button><button id="calculateCountryRisk" class="btn btn-primary"><i class="bi bi-calculator"></i> Hitung Risiko AJAX</button></div></div>
<div class="row g-4 mb-4">
    <div class="col-lg-4"><div class="card h-100"><div class="card-body"><h5>Informasi Umum</h5><dl class="row mt-4"><dt class="col-5">Ibu Kota</dt><dd class="col-7">{{ $country->capital ?: '-' }}</dd><dt class="col-5">Wilayah</dt><dd class="col-7">{{ $country->region }}</dd><dt class="col-5">Subwilayah</dt><dd class="col-7">{{ $country->subregion }}</dd><dt class="col-5">Bahasa</dt><dd class="col-7">{{ $country->language }}</dd><dt class="col-5">Mata Uang</dt><dd class="col-7">{{ $country->currency_code }} — {{ $country->currency_name }}</dd><dt class="col-5">Populasi</dt><dd class="col-7">{{ number_format($country->population ?? 0) }}</dd></dl></div></div></div>
    <div class="col-lg-4"><div class="card h-100"><div class="card-body"><h5>Ekonomi Terbaru</h5><p class="text-muted">Tahun {{ $economic?->year ?: '-' }}</p><dl class="row"><dt class="col-5">GDP</dt><dd class="col-7">{{ $economic?->gdp ? '$'.number_format($economic->gdp/1e9,2).' Miliar' : '-' }}</dd><dt class="col-5">Inflasi</dt><dd class="col-7">{{ $economic?->inflation!==null ? number_format($economic->inflation,2).'%' : '-' }}</dd><dt class="col-5">Ekspor</dt><dd class="col-7">{{ $economic?->exports ? '$'.number_format($economic->exports/1e9,2).' Miliar' : '-' }}</dd><dt class="col-5">Impor</dt><dd class="col-7">{{ $economic?->imports ? '$'.number_format($economic->imports/1e9,2).' Miliar' : '-' }}</dd></dl></div></div></div>
    <div class="col-lg-4"><div class="card h-100"><div class="card-body"><h5>Cuaca Saat Ini</h5><p class="text-muted">{{ $weather?->condition ?: 'Belum tersedia' }}</p><dl class="row"><dt class="col-6">Temperatur</dt><dd class="col-6">{{ $weather?->temperature!==null?number_format($weather->temperature,1).'°C':'-' }}</dd><dt class="col-6">Terasa</dt><dd class="col-6">{{ $weather?->apparent_temperature!==null?number_format($weather->apparent_temperature,1).'°C':'-' }}</dd><dt class="col-6">Kelembapan</dt><dd class="col-6">{{ $weather?->humidity!==null?number_format($weather->humidity,0).'%':'-' }}</dd><dt class="col-6">Angin</dt><dd class="col-6">{{ $weather?->wind_speed!==null?number_format($weather->wind_speed,1).' km/jam':'-' }}</dd><dt class="col-6">Risiko Badai</dt><dd class="col-6">{{ $weather?->storm_risk!==null?number_format($weather->storm_risk,1).'/100':'-' }}</dd></dl></div></div></div>
</div>
<div class="row g-4"><div class="col-lg-8"><div class="card"><div class="card-body"><h5>Tren GDP dan Inflasi 10 Tahun</h5><canvas id="economicChart" height="120"></canvas></div></div></div><div class="col-lg-4"><div class="card h-100"><div class="card-body text-center"><div class="text-muted">Risiko Terakhir</div><div id="countryRiskScore" class="display-3 fw-bold text-primary">{{ $risk?number_format($risk->total_score,1):'-' }}</div><span id="countryRiskLevel" class="badge {{ $risk?($risk->risk_level==='Rendah'?'badge-low':($risk->risk_level==='Sedang'?'badge-medium':'badge-high')):'text-bg-secondary' }}">{{ $risk?'Risiko '.$risk->risk_level:'Belum dihitung' }}</span><div id="riskComponents" class="text-start mt-4 small">@foreach($risk?->components ?? [] as $component)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $component->component }} ({{ number_format($component->weight,0) }}%)</span><strong>{{ number_format($component->weighted_score,1) }}</strong></div>@endforeach</div></div></div></div></div>
@endsection
@push('scripts')
<script>
new Chart(document.getElementById('economicChart'),{type:'line',data:{labels:@json($economics->pluck('year')),datasets:[{label:'GDP (Miliar USD)',data:@json($economics->map(fn($e)=>$e->gdp?round($e->gdp/1e9,2):null)),yAxisID:'y',tension:.25},{label:'Inflasi (%)',data:@json($economics->pluck('inflation')),yAxisID:'y1',tension:.25}]},options:{responsive:true,interaction:{mode:'index',intersect:false},scales:{y:{position:'left'},y1:{position:'right',grid:{drawOnChartArea:false}}}}});
document.getElementById('watchCountry').addEventListener('click',async()=>{sg.loading(true);try{const p=await sg.fetchJson('{{ route('watchlists.store',$country) }}',{method:'POST'});sg.toast(p.message)}catch(e){sg.toast(e.message,false)}finally{sg.loading(false)}});
document.getElementById('calculateCountryRisk').addEventListener('click',async()=>{sg.loading(true);try{const p=await sg.fetchJson('{{ route('risk.calculate',$country) }}',{method:'POST'});const r=p.data;document.getElementById('countryRiskScore').textContent=sg.number(r.total_score,1);const badge=document.getElementById('countryRiskLevel');badge.className=`badge ${sg.riskClass(r.risk_level)}`;badge.textContent=`Risiko ${r.risk_level}`;document.getElementById('riskComponents').innerHTML=(r.components||[]).map(c=>`<div class="d-flex justify-content-between border-bottom py-2"><span>${sg.escape(c.component)} (${sg.number(c.weight,0)}%)</span><strong>${sg.number(c.weighted_score,1)}</strong></div>`).join('');sg.toast(p.message)}catch(e){sg.toast(e.message,false)}finally{sg.loading(false)}});
</script>
@endpush
