@extends('layouts.app')
@section('title','Analisis Risiko')
@section('heading','Analisis Risiko')
@section('content')
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h2 class="page-title">Mesin Skor Risiko</h2><p class="text-muted mb-0">Weighted Risk Model: cuaca 30%, inflasi 20%, berita 40%, mata uang 10%.</p></div><span class="badge text-bg-light border">Skala 0–100</span></div>
<div class="card mb-4"><div class="card-body"><form id="riskForm" class="row g-3 align-items-end"><div class="col-lg-9"><label class="form-label">Negara</label><select id="riskCountry" class="form-select" required><option value="">Pilih negara yang akan dianalisis</option>@foreach($countries as $c)<option value="{{ $c->id }}" @selected($selected?->id===$c->id)>{{ $c->name }}</option>@endforeach</select></div><div class="col-lg-3 d-grid"><button class="btn btn-primary"><i class="bi bi-calculator me-1"></i> Hitung via AJAX</button></div></form></div></div>
<div id="riskResult" class="row g-4 mb-4 {{ $score?'':'d-none' }}"><div class="col-lg-4"><div class="card h-100"><div class="card-body text-center"><div id="riskCountryName" class="text-muted">Skor Risiko {{ $selected?->name }}</div><div id="riskTotal" class="display-2 fw-bold text-primary">{{ $score?number_format($score->total_score,1):'-' }}</div><span id="riskLevel" class="badge fs-6 {{ $score?($score->risk_level==='Rendah'?'badge-low':($score->risk_level==='Sedang'?'badge-medium':'badge-high')):'' }}">{{ $score?'Risiko '.$score->risk_level:'-' }}</span><div id="riskTime" class="small text-muted mt-3">{{ $score?->calculated_at?->format('d/m/Y H:i') }}</div></div></div></div><div class="col-lg-8"><div class="card h-100"><div class="card-body"><h5>Komponen dan Bobot</h5><canvas id="riskChart" height="110"></canvas></div></div></div></div>
<div id="componentCards" class="row g-3 mb-4"></div>
<div class="card"><div class="card-header bg-white border-0 pt-4 px-4"><h5>Riwayat Perhitungan</h5></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Negara</th><th>Cuaca</th><th>Inflasi</th><th>Mata Uang</th><th>Berita</th><th>Total</th><th>Tingkat</th></tr></thead><tbody id="riskHistory">@forelse($latest as $r)<tr><td>{{ $r->country?->name }}</td><td>{{ number_format($r->weather_score,1) }}</td><td>{{ number_format($r->inflation_score,1) }}</td><td>{{ number_format($r->currency_score,1) }}</td><td>{{ number_format($r->news_score,1) }}</td><td><strong>{{ number_format($r->total_score,1) }}</strong></td><td><span class="badge {{ $r->risk_level==='Rendah'?'badge-low':($r->risk_level==='Sedang'?'badge-medium':'badge-high') }}">{{ $r->risk_level }}</span></td></tr>@empty<tr><td colspan="7" class="text-center text-muted py-4">Belum ada perhitungan risiko.</td></tr>@endforelse</tbody></table></div><div class="card-footer bg-white">{{ $latest->links() }}</div></div>
@endsection
@push('scripts')
<script>
let riskChart;
function renderScore(score){
    if(!score)return;document.getElementById('riskResult').classList.remove('d-none');document.getElementById('riskCountryName').textContent=`Skor Risiko ${score.country?.name||''}`;document.getElementById('riskTotal').textContent=sg.number(score.total_score,1);const level=document.getElementById('riskLevel');level.textContent=`Risiko ${score.risk_level}`;level.className=`badge fs-6 ${sg.riskClass(score.risk_level)}`;document.getElementById('riskTime').textContent=score.calculated_at?new Date(score.calculated_at).toLocaleString('id-ID'):'-';
    const components=score.components||[];const labels=components.length?components.map(x=>x.component):['Cuaca','Inflasi','Mata Uang','Berita'];const scores=components.length?components.map(x=>x.normalized_score):[score.weather_score,score.inflation_score,score.currency_score,score.news_score];if(riskChart)riskChart.destroy();riskChart=new Chart(document.getElementById('riskChart'),{type:'bar',data:{labels,datasets:[{label:'Skor Normalisasi',data:scores},{label:'Kontribusi Berbobot',data:components.map(x=>x.weighted_score)}]},options:{responsive:true,scales:{y:{beginAtZero:true,max:100}}}});
    document.getElementById('componentCards').innerHTML=components.map(c=>`<div class="col-md-6 col-xl-3"><div class="card h-100"><div class="card-body"><div class="d-flex justify-content-between"><strong>${sg.escape(c.component)}</strong><span class="badge text-bg-light border">Bobot ${sg.number(c.weight,0)}%</span></div><div class="fs-3 fw-bold text-primary my-2">${sg.number(c.weighted_score,2)}</div><div class="small">Nilai asli: ${sg.number(c.raw_value,2)}<br>Normalisasi: ${sg.number(c.normalized_score,2)}</div><p class="small text-muted mt-2 mb-0">${sg.escape(c.notes||'')}</p></div></div></div>`).join('');
}
renderScore(@json($score));
document.getElementById('riskForm').addEventListener('submit',async e=>{e.preventDefault();const id=document.getElementById('riskCountry').value;if(!id)return;sg.loading(true);try{const payload=await sg.fetchJson(`{{ url('/api/risk/country') }}/${id}/calculate`,{method:'POST'});renderScore(payload.data);const r=payload.data;document.getElementById('riskHistory').insertAdjacentHTML('afterbegin',`<tr><td>${sg.escape(r.country?.name||'-')}</td><td>${sg.number(r.weather_score,1)}</td><td>${sg.number(r.inflation_score,1)}</td><td>${sg.number(r.currency_score,1)}</td><td>${sg.number(r.news_score,1)}</td><td><strong>${sg.number(r.total_score,1)}</strong></td><td><span class="badge ${sg.riskClass(r.risk_level)}">${sg.escape(r.risk_level)}</span></td></tr>`);sg.toast('Skor risiko dan rincian bobot berhasil dihitung.');history.replaceState({},'',`{{ route('risk.index') }}?country=${id}`);}catch(err){sg.toast(err.message,false);}finally{sg.loading(false);}});
</script>
@endpush
