@extends('layouts.app')
@section('title','Dampak Nilai Tukar')
@section('heading','Dampak Nilai Tukar')
@section('content')
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h2 class="page-title">Nilai Tukar Mata Uang</h2><p class="text-muted mb-0">Pantau kurs terkini, riwayat 30 hari, dan simulasi konversi.</p></div><span class="badge text-bg-light border">ExchangeRate-API + Frankfurter</span></div>
<div class="card mb-4"><div class="card-body"><form id="currencyForm" class="row g-3 align-items-end"><div class="col-lg-9"><label class="form-label">Mata uang tujuan</label><select id="targetCurrency" class="form-select">@foreach($countries->unique('currency_code') as $c)<option value="{{ $c->currency_code }}" @selected($target===$c->currency_code)>{{ $c->currency_code }} â€” {{ $c->currency_name }} ({{ $c->name }})</option>@endforeach</select></div><div class="col-lg-3 d-grid"><button class="btn btn-primary"><i class="bi bi-arrow-repeat me-1"></i> Perbarui Data</button></div></form></div></div>
<div class="row g-4 mb-4"><div class="col-lg-4"><div class="card h-100"><div class="card-body"><div class="text-muted">1 USD setara dengan</div><div id="rateValue" class="display-5 fw-bold text-primary mt-2">{{ $rate?number_format($rate->rate,4):'-' }}</div><div id="rateTarget" class="fs-5">{{ $target }}</div><hr><div>Perubahan: <strong id="rateChange" class="{{ ($rate?->change_percent??0)>=0?'text-success':'text-danger' }}">{{ $rate?number_format($rate->change_percent,4):'-' }}%</strong></div><small id="rateTime" class="text-muted">{{ $rate?->recorded_at?->format('d M Y H:i') }}</small></div></div></div><div class="col-lg-8"><div class="card h-100"><div class="card-body"><h5>Tren 30 Hari</h5><canvas id="currencyChart" height="120"></canvas><div id="historyEmpty" class="text-center text-muted py-4 d-none">Riwayat kurs belum tersedia.</div></div></div></div></div>
<div class="card"><div class="card-body"><h5>Simulasi Dampak Biaya Impor</h5><form id="convertForm" class="row g-3 align-items-end mt-1"><div class="col-md-4"><label class="form-label">Jumlah USD</label><input id="amount" type="number" min="0" step="0.01" value="1000" class="form-control" required></div><div class="col-md-4"><label class="form-label">Hasil dalam <span id="convertTargetLabel">{{ $target }}</span></label><input id="convertResult" class="form-control" value="-" readonly></div><div class="col-md-4 d-grid"><button class="btn btn-outline-primary">Konversikan</button></div></form></div></div>
@endsection
@push('scripts')
<script>
let chart;
function renderChart(rows,target){const canvas=document.getElementById('currencyChart');if(chart)chart.destroy();const data=rows||[];document.getElementById('historyEmpty').classList.toggle('d-none',data.length>0);chart=new Chart(canvas,{type:'line',data:{labels:data.map(x=>new Date(x.rate_date||x.recorded_at).toLocaleDateString('id-ID')),datasets:[{label:`USD/${target}`,data:data.map(x=>Number(x.rate)),tension:.3,fill:true}]},options:{responsive:true,interaction:{mode:'index',intersect:false},scales:{y:{beginAtZero:false}}}});}
function renderRate(rate,target){document.getElementById('rateValue').textContent=rate?sg.number(rate.rate,4):'-';document.getElementById('rateTarget').textContent=target;document.getElementById('convertTargetLabel').textContent=target;const change=document.getElementById('rateChange');change.textContent=rate?`${sg.number(rate.change_percent,4)}%`:'-';change.className=Number(rate?.change_percent||0)>=0?'text-success':'text-danger';document.getElementById('rateTime').textContent=rate?.recorded_at?new Date(rate.recorded_at).toLocaleString('id-ID'):'-';}
renderRate(@json($rate),'{{ $target }}');renderChart(@json($history),'{{ $target }}');
document.getElementById('currencyForm').addEventListener('submit',async e=>{e.preventDefault();const target=document.getElementById('targetCurrency').value;sg.loading(true);try{const [latest,historyPayload]=await Promise.all([sg.fetchJson(`{{ url('/api/currency') }}?base=USD&target=${target}&force=1`),sg.fetchJson(`{{ url('/api/currency/history') }}?base=USD&target=${target}&days=30&force=1`)]);renderRate(latest.data,target);renderChart(historyPayload.data,target);window.history.replaceState({},'',`{{ route('currency.index') }}?target=${target}`);sg.toast('Kurs dan riwayat berhasil diperbarui.');}catch(err){sg.toast(err.message,false);}finally{sg.loading(false);}});
document.getElementById('convertForm').addEventListener('submit',async e=>{e.preventDefault();const target=document.getElementById('targetCurrency').value,amount=document.getElementById('amount').value;sg.loading(true);try{const payload=await sg.fetchJson(`{{ url('/api/currency/convert') }}?amount=${encodeURIComponent(amount)}&base=USD&target=${target}`);document.getElementById('convertResult').value=`${sg.number(payload.data.result,2)} ${target}`;}catch(err){sg.toast(err.message,false);}finally{sg.loading(false);}});
</script>
@endpush
