<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::create('countries',function(Blueprint $t){$t->id();$t->string('name');$t->string('official_name')->nullable();$t->string('code',2)->unique();$t->string('cca3',3)->nullable()->unique();$t->string('region')->nullable();$t->string('subregion')->nullable();$t->string('capital')->nullable();$t->string('currency_code',5)->nullable();$t->string('currency_name')->nullable();$t->string('language')->nullable();$t->string('flag_url')->nullable();$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->unsignedBigInteger('population')->nullable();$t->timestamps();});
  Schema::create('country_economics',function(Blueprint $t){$t->id();$t->foreignId('country_id')->constrained()->cascadeOnDelete();$t->year('year');$t->decimal('gdp',20,2)->nullable();$t->decimal('inflation',10,4)->nullable();$t->decimal('exports',20,2)->nullable();$t->decimal('imports',20,2)->nullable();$t->unsignedBigInteger('population')->nullable();$t->timestamps();$t->unique(['country_id','year']);});
  Schema::create('weather_data',function(Blueprint $t){$t->id();$t->foreignId('country_id')->constrained()->cascadeOnDelete();$t->decimal('temperature',8,2)->nullable();$t->decimal('precipitation',8,2)->nullable();$t->decimal('wind_speed',8,2)->nullable();$t->integer('weather_code')->nullable();$t->decimal('storm_risk',8,2)->default(0);$t->timestamp('observed_at')->nullable();$t->timestamps();});
  Schema::create('currency_rates',function(Blueprint $t){$t->id();$t->string('base_currency',5);$t->string('target_currency',5);$t->decimal('rate',18,6);$t->decimal('change_percent',10,4)->default(0);$t->timestamp('recorded_at');$t->timestamps();$t->index(['base_currency','target_currency']);});
  Schema::create('risk_scores',function(Blueprint $t){$t->id();$t->foreignId('country_id')->constrained()->cascadeOnDelete();$t->decimal('weather_score',8,2);$t->decimal('inflation_score',8,2);$t->decimal('currency_score',8,2);$t->decimal('news_score',8,2);$t->decimal('total_score',8,2);$t->string('risk_level');$t->timestamp('calculated_at');$t->timestamps();});
  Schema::create('risk_components',function(Blueprint $t){$t->id();$t->foreignId('risk_score_id')->constrained()->cascadeOnDelete();$t->string('component');$t->decimal('raw_value',14,4)->nullable();$t->decimal('normalized_score',8,2);$t->decimal('weight',8,2);$t->decimal('weighted_score',8,2);$t->text('notes')->nullable();$t->timestamps();});
  Schema::create('ports',function(Blueprint $t){$t->id();$t->foreignId('country_id')->nullable()->constrained()->nullOnDelete();$t->string('name');$t->string('unlocode')->nullable()->unique();$t->string('city')->nullable();$t->string('country_name');$t->decimal('latitude',10,7);$t->decimal('longitude',10,7);$t->string('port_type')->default('Pelabuhan Laut');$t->string('status')->default('Aktif');$t->timestamps();});
  Schema::create('news_cache',function(Blueprint $t){$t->id();$t->foreignId('country_id')->nullable()->constrained()->nullOnDelete();$t->string('title');$t->text('description')->nullable();$t->text('url')->nullable();$t->text('image_url')->nullable();$t->string('source')->nullable();$t->timestamp('published_at')->nullable();$t->string('sentiment')->default('Netral');$t->integer('positive_score')->default(0);$t->integer('negative_score')->default(0);$t->string('query')->nullable();$t->timestamps();});
  Schema::create('news_sentiments',function(Blueprint $t){$t->id();$t->foreignId('news_cache_id')->constrained('news_cache')->cascadeOnDelete();$t->string('sentiment');$t->integer('positive_count')->default(0);$t->integer('negative_count')->default(0);$t->integer('neutral_count')->default(0);$t->json('matched_positive')->nullable();$t->json('matched_negative')->nullable();$t->timestamps();});
  Schema::create('watchlists',function(Blueprint $t){$t->id();$t->foreignId('user_id')->constrained()->cascadeOnDelete();$t->foreignId('country_id')->constrained()->cascadeOnDelete();$t->text('notes')->nullable();$t->timestamps();$t->unique(['user_id','country_id']);});
  Schema::create('articles',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('title');$t->string('slug')->unique();$t->text('excerpt')->nullable();$t->longText('content');$t->string('status')->default('draft');$t->timestamp('published_at')->nullable();$t->timestamps();});
  Schema::create('positive_words',function(Blueprint $t){$t->id();$t->string('word')->unique();$t->timestamps();});
  Schema::create('negative_words',function(Blueprint $t){$t->id();$t->string('word')->unique();$t->timestamps();});
  Schema::create('api_logs',function(Blueprint $t){$t->id();$t->string('service');$t->text('endpoint');$t->string('method',10)->default('GET');$t->integer('status_code')->nullable();$t->integer('response_time_ms')->nullable();$t->boolean('success')->default(false);$t->text('message')->nullable();$t->timestamp('requested_at');$t->timestamps();});
  Schema::create('country_comparisons',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('country_a_id')->constrained('countries')->cascadeOnDelete();$t->foreignId('country_b_id')->constrained('countries')->cascadeOnDelete();$t->json('result')->nullable();$t->timestamps();});
  Schema::create('notifications',function(Blueprint $t){$t->uuid('id')->primary();$t->string('type');$t->morphs('notifiable');$t->text('data');$t->timestamp('read_at')->nullable();$t->timestamps();});
  Schema::create('system_settings',function(Blueprint $t){$t->id();$t->string('key')->unique();$t->text('value')->nullable();$t->string('type')->default('string');$t->text('description')->nullable();$t->timestamps();});
 }
 public function down():void{foreach(['system_settings','notifications','country_comparisons','api_logs','negative_words','positive_words','articles','watchlists','news_sentiments','news_cache','ports','risk_components','risk_scores','currency_rates','weather_data','country_economics','countries'] as $table) Schema::dropIfExists($table);}
};
