@extends('layouts.app')
@section('title','Perbandingan Negara')
@section('heading','Perbandingan Negara')
@section('content')
<div class="mb-4"><h2 class="page-title">Bandingkan Dua Negara</h2><p class="text-muted mb-0">Perbandingan GDP, inflasi, cuaca, kurs, dan risiko secara langsung.</p></div>
<div class="card mb-4"><div class="card-body"><form id="comparisonForm" class="row g-3 align-items-end"><div class="col-lg-5"><label class="form-label">Negara pertama</label><select id="countryA" class="form-select" required><option value="">Pilih negara</option>@foreach($countries as $c)<option value="{{ $c->id }}" @selected($a?->id===$c->id)>{{ $c->name }}</option>@endforeach</select></div><div class="col-lg-5"><label class="form-label">Negara kedua</label><select id="countryB" class="form-select" required><option value="">Pilih negara</option>@foreach($countries as $c)<option value="{{ $c->id }}" @selected($b?->id===$c->id)>{{ $c->name }}</option>@endforeach</select></div><div class="col-lg-2 d-grid"><button class="btn btn-primary">Bandingkan AJAX</button></div></form></div></div>
<div id="comparisonResult" class="d-none"><div class="row g-4 mb-4"><div class="col-lg-7"><div class="card h-100"><div class="table-responsive"><table class="table table-bordered align-middle mb-0"><thead><tr><th>Indikator</th><th id="headA">A</th><th id="headB">B</th></tr></thead><tbody id="comparisonRows"></tbody></table></div></div></div><div class="col-lg-5"><div class="card h-100"><div class="card-body"><h5>Grafik Indeks Perbandingan</h5><canvas id="comparisonChart"></canvas><small class="text-muted">GDP ditampilkan dalam miliar USD; indikator lain memakai nilainya masing-masing.</small></div></div></div></div></div>
@endsection
@push('scripts')
<script>
let compareChart;
function renderSide(data){return {name:data.country.name,gdp:Number(data.economic?.gdp||0)/1e9,inflation:Number(data.economic?.inflation||0),temperature:Number(data.weather?.temperature||0),wind:Number(data.weather?.wind_speed||0),currency:Number(data.currency?.rate||0),currencyCode:data.country.currency_code||'-',risk:Number(data.risk?.total_score||0),riskLevel:data.risk?.risk_level||'-'};}
function renderComparison(payload){const a=renderSide(payload.a),b=renderSide(payload.b);document.getElementById('comparisonResult').classList.remove('d-none');document.getElementById('headA').textContent=a.name;document.getElementById('headB').textContent=b.name;const rows=[['GDP',`${sg.number(a.gdp,2)} miliar USD`,`${sg.number(b.gdp,2)} miliar USD`],['Inflasi',`${sg.number(a.inflation,2)}%`,`${sg.number(b.inflation,2)}%`],['Temperatur',`${sg.number(a.temperature,1)}°C`,`${sg.number(b.temperature,1)}°C`],['Kecepatan angin',`${sg.number(a.wind,1)} km/jam`,`${sg.number(b.wind,1)} km/jam`],['1 USD',`${sg.number(a.currency,4)} ${a.currencyCode}`,`${sg.number(b.currency,4)} ${b.currencyCode}`],['Skor Risiko',`${sg.number(a.risk,1)} — ${a.riskLevel}`,`${sg.number(b.risk,1)} — ${b.riskLevel}`]];document.getElementById('comparisonRows').innerHTML=rows.map(r=>`<tr><th>${r[0]}</th><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('');if(compareChart)compareChart.destroy();compareChart=new Chart(document.getElementById('comparisonChart'),{type:'radar',data:{labels:['GDP (miliar)','Inflasi','Temperatur','Angin','Risiko'],datasets:[{label:a.name,data:[a.gdp,a.inflation,a.temperature,a.wind,a.risk]},{label:b.name,data:[b.gdp,b.inflation,b.temperature,b.wind,b.risk]}]},options:{responsive:true,scales:{r:{beginAtZero:true}}}});}
@if($result)renderComparison(@json($result));@endif
document.getElementById('comparisonForm').addEventListener('submit',async e=>{e.preventDefault();const a=document.getElementById('countryA').value,b=document.getElementById('countryB').value;if(a===b){sg.toast('Pilih dua negara yang berbeda.',false);return;}sg.loading(true);try{const payload=await sg.fetchJson(`{{ url('/api/comparison') }}?a=${a}&b=${b}`);renderComparison(payload.data);history.replaceState({},'',`{{ route('comparison.index') }}?a=${a}&b=${b}`);sg.toast('Perbandingan berhasil dibuat.');}catch(err){sg.toast(err.message,false);}finally{sg.loading(false);}});
</script>
@endpush
