@extends('layouts.app')
@section('title','Lokasi Pelabuhan')
@section('heading','Lokasi Pelabuhan Dunia')
@section('content')
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h2 class="page-title">Peta Pelabuhan Global</h2><p class="text-muted mb-0">Cari nama, kota, negara, UN/LOCODE, atau nomor World Port Index.</p></div><span class="badge text-bg-light border"><span id="portCount">{{ $mapPorts->count() }}</span> marker ditampilkan</span></div>
<div class="card mb-4"><div class="card-body"><form id="portForm" class="row g-3 align-items-end"><div class="col-lg-6"><label class="form-label">Pencarian</label><input id="portQuery" class="form-control" value="{{ request('q') }}" placeholder="Contoh: Tanjung Priok, Indonesia, IDTPP..."></div><div class="col-lg-4"><label class="form-label">Filter negara</label><select id="portCountry" class="form-select"><option value="">Semua negara</option>@foreach($portCountries as $name)<option @selected(request('country')===$name)>{{ $name }}</option>@endforeach</select></div><div class="col-lg-2 d-grid"><button class="btn btn-primary"><i class="bi bi-search me-1"></i> Cari AJAX</button></div></form></div></div>
<div class="card mb-4"><div class="card-body p-2"><div id="portsMap" class="map"></div></div></div>
<div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Pelabuhan</th><th>Kode</th><th>Kota</th><th>Negara</th><th>Sumber</th><th>Status</th></tr></thead><tbody id="portRows"></tbody></table></div><div class="card-footer bg-white small text-muted">Tabel AJAX menampilkan maksimal 30 hasil pertama; peta dapat menampilkan sampai 1.000 marker.</div></div>
@endsection
@push('scripts')
<script>
const map=L.map('portsMap').setView([0,110],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);const layer=L.layerGroup().addTo(map);
function renderMap(items){layer.clearLayers();items.forEach(p=>{if(p.latitude===null||p.longitude===null)return;L.marker([p.latitude,p.longitude]).bindPopup(`<strong>${sg.escape(p.name)}</strong><br>${sg.escape(p.city||'')}, ${sg.escape(p.country_name)}<br>UN/LOCODE: ${sg.escape(p.unlocode||'-')}<br>WPI: ${sg.escape(p.wpi_number||'-')}`).addTo(layer);});document.getElementById('portCount').textContent=items.length;if(items.length===1)map.setView([items[0].latitude,items[0].longitude],7);}
function renderRows(items){document.getElementById('portRows').innerHTML=items.length?items.map(p=>`<tr><td><strong>${sg.escape(p.name)}</strong><div class="small text-muted">WPI: ${sg.escape(p.wpi_number||'-')}</div></td><td>${sg.escape(p.unlocode||'-')}</td><td>${sg.escape(p.city||'-')}</td><td>${sg.escape(p.country_name)}</td><td><span class="badge text-bg-light border">${sg.escape(p.data_source||'Manual')}</span></td><td><span class="badge text-bg-success">${sg.escape(p.status||'Aktif')}</span></td></tr>`).join(''):'<tr><td colspan="6" class="text-center text-muted py-4">Pelabuhan tidak ditemukan.</td></tr>';}
const initialMap=@json($mapPorts);const initialRows=@json($ports->items());renderMap(initialMap);renderRows(initialRows);
document.getElementById('portForm').addEventListener('submit',async e=>{e.preventDefault();const q=document.getElementById('portQuery').value,country=document.getElementById('portCountry').value,params=new URLSearchParams({q,country});sg.loading(true);try{const [markers,table]=await Promise.all([sg.fetchJson(`{{ url('/api/ports/map') }}?${params}&limit=1000`),sg.fetchJson(`{{ url('/api/ports') }}?${params}&per_page=30`)]);renderMap(markers.data||[]);renderRows(table.data?.data||[]);sg.toast(`${markers.data?.length||0} lokasi pelabuhan ditemukan.`);history.replaceState({},'',`{{ route('ports.index') }}?${params}`);}catch(err){sg.toast(err.message,false);}finally{sg.loading(false);}});
</script>
@endpush
