@extends('layouts.app')
@section('title','Kelola Pelabuhan')
@section('heading','Kelola Dataset Pelabuhan')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><h2 class="page-title">Dataset Pelabuhan</h2><p class="text-muted mb-0">Tambah manual, ubah, hapus, atau impor CSV World Port Index.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addPort"><i class="bi bi-plus-lg me-1"></i> Tambah Pelabuhan</button></div>
<div class="row g-4 mb-4"><div class="col-xl-7"><div class="card h-100"><div class="card-body"><h5>Import Dataset CSV</h5><p class="text-muted small">Kolom yang dikenali antara lain: <code>MAIN_PORT_NAME</code>, <code>COUNTRY</code>, <code>LATITUDE</code>, <code>LONGITUDE</code>, <code>UN_LOCODE</code>, dan <code>WORLD_PORT_INDEX_NUMBER</code>.</p><form method="POST" action="{{ route('admin.ports.import') }}" enctype="multipart/form-data" class="row g-3 align-items-end">@csrf<div class="col-md-8"><label class="form-label">File CSV maksimal 20 MB</label><input type="file" name="file" accept=".csv,.txt" class="form-control" required></div><div class="col-md-4 d-grid"><button class="btn btn-outline-primary"><i class="bi bi-upload me-1"></i> Import Sekarang</button></div></form><a class="btn btn-sm btn-light border mt-3" href="{{ route('admin.ports.sample') }}"><i class="bi bi-download me-1"></i> Unduh contoh CSV</a></div></div></div><div class="col-xl-5"><div class="card h-100"><div class="card-body"><h5>Riwayat Import</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>File</th><th>Masuk</th><th>Lewat</th></tr></thead><tbody>@forelse($imports as $batch)<tr><td><span class="d-block text-truncate" style="max-width:180px">{{ $batch->filename }}</span><small class="text-muted">{{ $batch->created_at?->format('d/m/Y H:i') }}</small></td><td>{{ $batch->imported_rows }}</td><td>{{ $batch->skipped_rows }}</td></tr>@empty<tr><td colspan="3" class="text-muted">Belum ada import.</td></tr>@endforelse</tbody></table></div></div></div></div></div>
<div class="card"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Nama</th><th>Kode</th><th>Lokasi</th><th>Koordinat</th><th>Sumber</th><th>Aksi</th></tr></thead><tbody>@forelse($ports as $p)<tr><td><strong>{{ $p->name }}</strong><div class="small text-muted">WPI {{ $p->wpi_number ?: '-' }}</div></td><td>{{ $p->unlocode ?: '-' }}</td><td>{{ $p->city ?: '-' }}, {{ $p->country_name }}</td><td>{{ $p->latitude }}, {{ $p->longitude }}</td><td><span class="badge text-bg-light border">{{ $p->data_source }}</span></td><td><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#editPort{{ $p->id }}">Ubah</button><form method="POST" action="{{ route('admin.ports.destroy',$p) }}" onsubmit="return confirm('Hapus pelabuhan ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Hapus</button></form></div></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada pelabuhan.</td></tr>@endforelse</tbody></table></div><div class="card-footer bg-white">{{ $ports->links() }}</div></div>
<div class="modal fade" id="addPort" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="POST" action="{{ route('admin.ports.store') }}">@csrf<div class="modal-header"><h5>Tambah Pelabuhan</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('admin.ports.partials.form',['port'=>null])</div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan</button></div></form></div></div>
@foreach($ports as $p)<div class="modal fade" id="editPort{{ $p->id }}" tabindex="-1"><div class="modal-dialog modal-lg"><form class="modal-content" method="POST" action="{{ route('admin.ports.update',$p) }}">@csrf @method('PUT')<div class="modal-header"><h5>Ubah Pelabuhan</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('admin.ports.partials.form',['port'=>$p])</div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary">Simpan Perubahan</button></div></form></div></div>@endforeach
@endsection
